<?php

namespace App\Helpers;

class ProductData
{
    public static function getCategories(): array
    {
        return [
            [
                'id' => 'tops',
                'name' => 'Tops',
                'slug' => 'tops',
                'description' => 'Chic crop tops, casual shirts, office wear & statement party tops.',
                'image' => 'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=800&q=80',
                'count' => 10,
                'subcategories' => ['Casual Tops', 'Crop Tops', 'Printed Tops', 'Office Wear Tops', 'Party Wear Tops']
            ],
            [
                'id' => 'leggings',
                'name' => 'Leggings',
                'slug' => 'leggings',
                'description' => 'Ultra-stretchable, breathable 4-way cotton, ankle-length & festive churidars.',
                'image' => 'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?auto=format&fit=crop&w=800&q=80',
                'count' => 8,
                'subcategories' => ['Cotton Leggings', 'Ankle Length Leggings', 'Printed Leggings', 'Stretch Leggings', 'Basic Leggings']
            ],
            [
                'id' => 'kurtis',
                'name' => 'Kurtis',
                'slug' => 'kurtis',
                'description' => 'Handcrafted block prints, graceful Anarkalis, and everyday office straight kurtis.',
                'image' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
                'count' => 10,
                'subcategories' => ['Cotton Kurtis', 'Printed Kurtis', 'Anarkali Kurtis', 'Straight Kurtis', 'Office Wear Kurtis', 'Party Wear Kurtis']
            ],
            [
                'id' => 'maxi',
                'name' => 'Maxi Dresses',
                'slug' => 'maxi',
                'description' => 'Flowing tiered silhouettes, romantic bohemian florals, and evening party maxis.',
                'image' => 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
                'count' => 8,
                'subcategories' => ['Casual Maxi', 'Floral Maxi', 'Printed Maxi', 'Party Maxi', 'Ankle Length Maxi']
            ],
            [
                'id' => 'nightwear',
                'name' => 'Nightwear',
                'slug' => 'nightwear',
                'description' => 'Pure modal cotton PJ sets, cozy button-down night suits, and satin slips.',
                'image' => 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
                'count' => 8,
                'subcategories' => ['Night Suits', 'Night Dresses', 'Cotton Nightwear', 'Printed Nightwear', 'Lounge Wear']
            ],
        ];
    }

    public static function getProducts(): array
    {
        return [
            // TOPS (1-8)
            [
                'id' => 1,
                'name' => 'Floral Printed Smocked Peplum Top',
                'category' => 'Tops',
                'subcategory' => 'Printed Tops',
                'price' => 799,
                'old_price' => 1299,
                'discount' => 38,
                'rating' => 4.6,
                'reviews' => 142,
                'image' => 'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'colors' => ['Pink', 'White', 'Blue'],
                'color_codes' => ['#F4A7B9', '#FFFFFF', '#6C9BCF'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-TOP-001',
                'material' => '100% Breathable Georgette',
                'fit' => 'Regular Smocked Fit',
                'care' => 'Gentle Machine Wash in Cold Water',
                'description' => 'Flattering smocked bust with gentle ruffle shoulders and a playful peplum waistline. Perfect for casual brunches and weekend outings.',
                'featured' => true,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 2,
                'name' => 'Casual Cotton Ribbed Crop Top',
                'category' => 'Tops',
                'subcategory' => 'Crop Tops',
                'price' => 549,
                'old_price' => 899,
                'discount' => 39,
                'rating' => 4.4,
                'reviews' => 98,
                'image' => 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['White', 'Black', 'Pink'],
                'color_codes' => ['#FFFFFF', '#1A1A1A', '#F8C8DC'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-TOP-002',
                'material' => '95% Combed Cotton, 5% Spandex',
                'fit' => 'Slim Fit',
                'care' => 'Machine Wash with Similar Colors',
                'description' => 'A versatile wardrobe essential crafted with ribbed stretch cotton. Looks effortless paired with high-waisted denim or linen trousers.',
                'featured' => false,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 3,
                'name' => 'Formal Collar Linen Office Shirt Top',
                'category' => 'Tops',
                'subcategory' => 'Office Wear Tops',
                'price' => 1199,
                'old_price' => 1799,
                'discount' => 33,
                'rating' => 4.7,
                'reviews' => 180,
                'image' => 'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['White', 'Blue', 'Green'],
                'color_codes' => ['#FFFFFF', '#A0C4E2', '#A3B899'],
                'badge' => 'Trending',
                'stock' => true,
                'sku' => 'ZYR-TOP-003',
                'material' => 'Pure Organic Linen Blend',
                'fit' => 'Relaxed Tailored Fit',
                'care' => 'Dry Clean or Gentle Cold Hand Wash',
                'description' => 'Crisp structured collar with mother-of-pearl buttons. Designed to keep you poised and cool from morning boardroom meetings to evening dinner.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 4,
                'name' => 'Embroidered Broderie Puff Sleeve Top',
                'category' => 'Tops',
                'subcategory' => 'Casual Tops',
                'price' => 899,
                'old_price' => 1499,
                'discount' => 40,
                'rating' => 4.8,
                'reviews' => 210,
                'image' => 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['White', 'Yellow'],
                'color_codes' => ['#FFFFFF', '#FDFD96'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-TOP-004',
                'material' => '100% Schifli Cotton',
                'fit' => 'Regular Feminine Fit',
                'care' => 'Hand Wash Cold',
                'description' => 'Intricate eyelet embroidery across the neckline with volumetric puff sleeves. Timeless elegance reimagined for Indian summers.',
                'featured' => true,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 5,
                'name' => 'Lurex Metallic Shimmer Party Top',
                'category' => 'Tops',
                'subcategory' => 'Party Wear Tops',
                'price' => 1299,
                'old_price' => 1999,
                'discount' => 35,
                'rating' => 4.5,
                'reviews' => 84,
                'image' => 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Black', 'Pink'],
                'color_codes' => ['#1A1A1A', '#E0A9AF'],
                'badge' => 'Sale',
                'stock' => true,
                'sku' => 'ZYR-TOP-005',
                'material' => 'Shimmer Knit with Satin Lining',
                'fit' => 'Cowl Neck Glam Fit',
                'care' => 'Dry Clean Only',
                'description' => 'Glow through sunset soirees and celebration nights with this fluid lurex cowl drape.',
                'featured' => false,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 6,
                'name' => 'Boho Tie-Front Tropical Printed Top',
                'category' => 'Tops',
                'subcategory' => 'Printed Tops',
                'price' => 699,
                'old_price' => 1099,
                'discount' => 36,
                'rating' => 4.3,
                'reviews' => 67,
                'image' => 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Green', 'Yellow'],
                'color_codes' => ['#4E7051', '#F7D070'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-TOP-006',
                'material' => 'Modal Rayon',
                'fit' => 'Boxy Tie Knot',
                'care' => 'Machine Wash Warm',
                'description' => 'Vibrant botanical print with adjustable front bow tie and breathable cap sleeves.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 7,
                'name' => 'Sleeveless Wrap V-Neck Satin Camisole',
                'category' => 'Tops',
                'subcategory' => 'Party Wear Tops',
                'price' => 749,
                'old_price' => 1199,
                'discount' => 38,
                'rating' => 4.6,
                'reviews' => 112,
                'image' => 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Pink', 'Black', 'White'],
                'color_codes' => ['#D4A5A5', '#111111', '#FFFFFF'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-TOP-007',
                'material' => 'Silky High-Grade Satin',
                'fit' => 'Bias Cut Body Skimming',
                'care' => 'Hand Wash in Cold Water',
                'description' => 'Ultra-luxurious satin handfeel with delicate spaghetti straps and flattering wrap drape.',
                'featured' => true,
                'best_seller' => true,
                'trending' => false,
            ],
            [
                'id' => 8,
                'name' => 'Minimalist Striped Cotton Tunic Top',
                'category' => 'Tops',
                'subcategory' => 'Casual Tops',
                'price' => 849,
                'old_price' => 1299,
                'discount' => 35,
                'rating' => 4.4,
                'reviews' => 89,
                'image' => 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['Blue', 'White'],
                'color_codes' => ['#5B84B1', '#FFFFFF'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-TOP-008',
                'material' => '100% Khadi Slub Cotton',
                'fit' => 'A-Line Tunic',
                'care' => 'Normal Machine Wash',
                'description' => 'Breathable yarn-dyed stripes with side slits and roll-up button sleeves.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],

            // LEGGINGS (9-16)
            [
                'id' => 9,
                'name' => 'Super Combed 4-Way Stretch Cotton Leggings',
                'category' => 'Leggings',
                'subcategory' => 'Cotton Leggings',
                'price' => 499,
                'old_price' => 799,
                'discount' => 38,
                'rating' => 4.8,
                'reviews' => 420,
                'image' => 'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['Black', 'White', 'Red', 'Pink'],
                'color_codes' => ['#1A1A1A', '#FFFFFF', '#B82E2E', '#F4A7B9'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-LEG-001',
                'material' => '95% Super Combed Cotton, 5% Elastane',
                'fit' => 'All-Day Gentle Hug Compression',
                'care' => 'Machine Washable',
                'description' => 'Crafted with premium bio-washed cotton and ultra-flexible 4-way stretch that never sags, bunches or goes see-through.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 10,
                'name' => 'Ankle Length Ultra Soft Lycra Leggings',
                'category' => 'Leggings',
                'subcategory' => 'Ankle Length Leggings',
                'price' => 449,
                'old_price' => 699,
                'discount' => 36,
                'rating' => 4.7,
                'reviews' => 340,
                'image' => 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Black', 'Blue', 'Pink'],
                'color_codes' => ['#1A1A1A', '#2B4C7E', '#D9899A'],
                'badge' => 'Trending',
                'stock' => true,
                'sku' => 'ZYR-LEG-002',
                'material' => 'Cotton Modal Lycra Blend',
                'fit' => 'Ankle Hugging Seamless Cuff',
                'care' => 'Machine Wash Warm',
                'description' => 'Modern ankle length cut designed specifically to wear seamlessly under kurtis, long tops, or athletic sneakers.',
                'featured' => false,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 11,
                'name' => 'Traditional Gathered Churidar Leggings',
                'category' => 'Leggings',
                'subcategory' => 'Basic Leggings',
                'price' => 599,
                'old_price' => 999,
                'discount' => 40,
                'rating' => 4.6,
                'reviews' => 210,
                'image' => 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'colors' => ['Red', 'Yellow', 'Green', 'Black'],
                'color_codes' => ['#C0392B', '#E5A93B', '#27AE60', '#1A1A1A'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-LEG-003',
                'material' => 'Pure Combed Compact Yarn',
                'fit' => 'Churidar Gathers at Ankle',
                'care' => 'Gentle Cycle Wash',
                'description' => 'Rich, multi-ring gathered churidar cuffs that pair exquisitely with ethnic suits, festive Anarkalis, and traditional kurtis.',
                'featured' => true,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 12,
                'name' => 'Ethnic Mandala Foil Printed Festive Leggings',
                'category' => 'Leggings',
                'subcategory' => 'Printed Leggings',
                'price' => 699,
                'old_price' => 1099,
                'discount' => 36,
                'rating' => 4.5,
                'reviews' => 118,
                'image' => 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Gold', 'Black', 'Red'],
                'color_codes' => ['#D4AF37', '#1A1A1A', '#922B21'],
                'badge' => 'Sale',
                'stock' => true,
                'sku' => 'ZYR-LEG-004',
                'material' => 'Cotton Elastane with Non-Crack Foil',
                'fit' => 'Form Fitting Festive Cut',
                'care' => 'Hand Wash Cold Inside Out',
                'description' => 'Delicate metallic gold foil borders on ankles that bring an opulent touch to celebratory festivities.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 13,
                'name' => 'High-Waist Tummy Control Seamless Shaper Leggings',
                'category' => 'Leggings',
                'subcategory' => 'Stretch Leggings',
                'price' => 899,
                'old_price' => 1499,
                'discount' => 40,
                'rating' => 4.9,
                'reviews' => 290,
                'image' => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Black', 'Blue'],
                'color_codes' => ['#1A1A1A', '#1E3A8A'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-LEG-005',
                'material' => 'Polyamide Microfiber & Lycra',
                'fit' => 'Targeted Core Compression',
                'care' => 'Cold Machine Wash',
                'description' => 'Wide 4-inch double layered compression waistband provides gentle midsection smoothing with squat-proof coverage.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 14,
                'name' => 'Pastel Toned Everyday Cotton Leggings',
                'category' => 'Leggings',
                'subcategory' => 'Basic Leggings',
                'price' => 429,
                'old_price' => 649,
                'discount' => 34,
                'rating' => 4.3,
                'reviews' => 145,
                'image' => 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Pink', 'Green', 'Yellow'],
                'color_codes' => ['#FADBD8', '#D4EFDF', '#FCF3CF'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-LEG-006',
                'material' => 'Organic Soft Bio-Cotton',
                'fit' => 'Regular Comfort Stretch',
                'care' => 'Machine Wash Cold',
                'description' => 'Soft sorbet pastel shades dyed with azo-free dyes that feel feather-light on sensitive skin.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 15,
                'name' => 'Floral Jacquard Textured Ankle Tights',
                'category' => 'Leggings',
                'subcategory' => 'Printed Leggings',
                'price' => 749,
                'old_price' => 1199,
                'discount' => 38,
                'rating' => 4.4,
                'reviews' => 76,
                'image' => 'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Black', 'Blue'],
                'color_codes' => ['#1A1A1A', '#2C3E50'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-LEG-007',
                'material' => 'Jacquard Textured Knit',
                'fit' => 'Ankle Crop',
                'care' => 'Gentle Machine Wash',
                'description' => 'Tone-on-tone self jacquard weave pattern that elevates any casual or formal outfit.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 16,
                'name' => 'Winter Thermal Fleece Lined Warm Leggings',
                'category' => 'Leggings',
                'subcategory' => 'Stretch Leggings',
                'price' => 999,
                'old_price' => 1599,
                'discount' => 38,
                'rating' => 4.7,
                'reviews' => 162,
                'image' => 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'colors' => ['Black', 'Blue'],
                'color_codes' => ['#1A1A1A', '#34495E'],
                'badge' => 'Sale',
                'stock' => true,
                'sku' => 'ZYR-LEG-008',
                'material' => 'Brushed Thermal Interior Cotton Poly',
                'fit' => 'Snug Insulated Fit',
                'care' => 'Delicate Cycle Wash',
                'description' => 'Plush velvety fleece lining preserves body heat without adding bulky silhouettes.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],

            // KURTIS (17-24)
            [
                'id' => 17,
                'name' => 'Handblock Printed Pure Cotton Straight Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Cotton Kurtis',
                'price' => 999,
                'old_price' => 1599,
                'discount' => 38,
                'rating' => 4.8,
                'reviews' => 320,
                'image' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['Pink', 'Blue', 'White'],
                'color_codes' => ['#E8A598', '#4A90E2', '#FFFFFF'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-KUR-001',
                'material' => '100% Bagru Handcrafted Cotton',
                'fit' => 'Calf Length Straight Cut',
                'care' => 'First Wash Dry Clean, Then Cold Gentle Wash',
                'description' => 'Authentic Jaipur wooden block prints with delicate threadwork on Mandarin placket and three-quarter sleeves.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 18,
                'name' => 'Floor Sweeping Flared Anarkali Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Anarkali Kurtis',
                'price' => 1699,
                'old_price' => 2599,
                'discount' => 35,
                'rating' => 4.9,
                'reviews' => 240,
                'image' => 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Red', 'Yellow', 'Pink'],
                'color_codes' => ['#A93226', '#F1C40F', '#E8B4B8'],
                'badge' => 'Trending',
                'stock' => true,
                'sku' => 'ZYR-KUR-002',
                'material' => 'Chanderi Silk Blend with Cotton Lining',
                'fit' => 'Full 32-Kali Flare Anarkali',
                'care' => 'Dry Clean Recommended',
                'description' => 'Grand voluminous Anarkali silhouette with Gota Patti lace borders, latkan tassel ties, and radiant festive charm.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 19,
                'name' => 'Minimalist Pintuck Office Wear Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Office Wear Kurtis',
                'price' => 849,
                'old_price' => 1299,
                'discount' => 35,
                'rating' => 4.5,
                'reviews' => 110,
                'image' => 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['White', 'Blue', 'Green'],
                'color_codes' => ['#FDFEFE', '#2980B9', '#27AE60'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-KUR-003',
                'material' => 'Slub Cotton Linen',
                'fit' => 'Straight Cut with Pocket',
                'care' => 'Machine Wash Cold',
                'description' => 'Smart vertical pintuck detailing on the yoke with a functional side pocket. Tailored for comfort through busy workdays.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 20,
                'name' => 'Chikankari Embroidered Pastel Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Straight Kurtis',
                'price' => 1399,
                'old_price' => 2199,
                'discount' => 36,
                'rating' => 4.9,
                'reviews' => 380,
                'image' => 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'colors' => ['Pink', 'White', 'Yellow'],
                'color_codes' => ['#FADBD8', '#FFFFFF', '#FEF9E7'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-KUR-004',
                'material' => 'Handwoven Georgette with Cotton Mulmul Slip',
                'fit' => 'Flowing Straight Fit',
                'care' => 'Gentle Hand Wash in Mild Detergent',
                'description' => 'Lucknowi artisan Chikankari needlework with Bakhiya and Phanda stitches. Sublime elegance for celebrations and family gatherings.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 21,
                'name' => 'Angrakha Style Peplum Festive Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Party Wear Kurtis',
                'price' => 1249,
                'old_price' => 1899,
                'discount' => 34,
                'rating' => 4.6,
                'reviews' => 95,
                'image' => 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Red', 'Green'],
                'color_codes' => ['#922B21', '#196F3D'],
                'badge' => 'Sale',
                'stock' => true,
                'sku' => 'ZYR-KUR-005',
                'material' => 'Art Silk Brocade Yoke',
                'fit' => 'Angrakha Overlap Fit',
                'care' => 'Dry Clean Only',
                'description' => 'Royal Mughal-inspired overlapping front panel with handmade potli buttons and metallic dori accents.',
                'featured' => false,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 22,
                'name' => 'Indigo Dabu Printed A-Line Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Printed Kurtis',
                'price' => 949,
                'old_price' => 1499,
                'discount' => 37,
                'rating' => 4.4,
                'reviews' => 88,
                'image' => 'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Blue', 'White'],
                'color_codes' => ['#1F4E79', '#FFFFFF'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-KUR-006',
                'material' => 'Natural Indigo Dyed Cotton',
                'fit' => 'A-Line Flare',
                'care' => 'Wash Separately in Cold Water',
                'description' => 'Heritage mud-resist Dabu technique prints on handspun cotton. Naturally cooling for warm weather.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 23,
                'name' => 'Embellished Mirror Work Chiffon Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Party Wear Kurtis',
                'price' => 1499,
                'old_price' => 2299,
                'discount' => 35,
                'rating' => 4.7,
                'reviews' => 134,
                'image' => 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Pink', 'Yellow'],
                'color_codes' => ['#E75480', '#F9E79F'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-KUR-007',
                'material' => 'Pure Poly Chiffon with Lining',
                'fit' => 'Straight Slit Cut',
                'care' => 'Dry Clean Only',
                'description' => 'Real reflective mirror embellishments along the neck and hem that catch every flicker of evening light.',
                'featured' => true,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 24,
                'name' => 'Tiered Bohemian Cotton Smocked Kurti',
                'category' => 'Kurtis',
                'subcategory' => 'Cotton Kurtis',
                'price' => 1099,
                'old_price' => 1699,
                'discount' => 35,
                'rating' => 4.6,
                'reviews' => 79,
                'image' => 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Green', 'Pink'],
                'color_codes' => ['#52BE80', '#F1948A'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-KUR-008',
                'material' => '100% Cambric Cotton',
                'fit' => 'Relaxed Tiered Silhouette',
                'care' => 'Machine Wash Cold',
                'description' => 'Three breezy tiers gathered beneath an elastic smocked bodice. Can be worn with leggings or styled as an ethnic dress.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],

            // MAXI DRESSES (25-32)
            [
                'id' => 25,
                'name' => 'Botanical Floral Tiered Ruffle Maxi Dress',
                'category' => 'Maxi',
                'subcategory' => 'Floral Maxi',
                'price' => 1499,
                'old_price' => 2399,
                'discount' => 38,
                'rating' => 4.8,
                'reviews' => 230,
                'image' => 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'colors' => ['Pink', 'White', 'Blue'],
                'color_codes' => ['#FADBD8', '#FFFFFF', '#A9CCE3'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-MAX-001',
                'material' => 'Airy Georgette with Crepe Lining',
                'fit' => 'Fit & Flare Flounced Silhouette',
                'care' => 'Gentle Machine Wash',
                'description' => 'Cascading tiered skirt with vintage botanical florals, sweetheart neckline, and adjustable tie straps.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 26,
                'name' => 'Bohemian Shirred Waist Maxi Sundress',
                'category' => 'Maxi',
                'subcategory' => 'Casual Maxi',
                'price' => 1199,
                'old_price' => 1899,
                'discount' => 37,
                'rating' => 4.6,
                'reviews' => 188,
                'image' => 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Yellow', 'Green'],
                'color_codes' => ['#F7DC6F', '#7DCEA0'],
                'badge' => 'Trending',
                'stock' => true,
                'sku' => 'ZYR-MAX-002',
                'material' => '100% Breathable Rayon Viscose',
                'fit' => 'Comfortable Shirred Waist',
                'care' => 'Cold Hand Wash',
                'description' => 'Sun-kissed boho print with a stretchy shirred waist and side pocket details. Great for holiday getaways and sunny day strolls.',
                'featured' => true,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 27,
                'name' => 'High-Slit Evening Satin Slip Maxi Dress',
                'category' => 'Maxi',
                'subcategory' => 'Party Maxi',
                'price' => 1799,
                'old_price' => 2799,
                'discount' => 36,
                'rating' => 4.9,
                'reviews' => 140,
                'image' => 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Black', 'Red', 'Pink'],
                'color_codes' => ['#1A1A1A', '#922B21', '#E8A598'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-MAX-003',
                'material' => 'Heavyweight Liquid Satin',
                'fit' => 'Body Skimming with Thigh High Slit',
                'care' => 'Dry Clean Only',
                'description' => 'Sculpted cowl neckline with a dramatic side slit and criss-cross strappy lace-up back.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 28,
                'name' => 'Geometric Printed Ankle Length Maxi Dress',
                'category' => 'Maxi',
                'subcategory' => 'Printed Maxi',
                'price' => 1299,
                'old_price' => 1999,
                'discount' => 35,
                'rating' => 4.4,
                'reviews' => 92,
                'image' => 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Black', 'White', 'Blue'],
                'color_codes' => ['#1A1A1A', '#FFFFFF', '#3498DB'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-MAX-004',
                'material' => 'Smooth Poly Moss Crepe',
                'fit' => 'Empire Waist Fit',
                'care' => 'Machine Wash Warm',
                'description' => 'Modern monochrome graphic print with flared godet inserts that create fluid movement as you walk.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 29,
                'name' => 'Embroidered Belted A-Line Resort Maxi',
                'category' => 'Maxi',
                'subcategory' => 'Ankle Length Maxi',
                'price' => 1599,
                'old_price' => 2499,
                'discount' => 36,
                'rating' => 4.7,
                'reviews' => 165,
                'image' => 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Pink'],
                'color_codes' => ['#FFFFFF', '#F5B7B1'],
                'badge' => 'Sale',
                'stock' => true,
                'sku' => 'ZYR-MAX-005',
                'material' => 'Linen Cotton Blend',
                'fit' => 'A-Line with Matching Fabric Sash Belt',
                'care' => 'Hand Wash Cold',
                'description' => 'Resort-ready crisp white fabric adorned with delicate floral thread embroidery on the collar and hem.',
                'featured' => false,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 30,
                'name' => 'Pleated Halter-Neck Chiffon Gown Maxi',
                'category' => 'Maxi',
                'subcategory' => 'Party Maxi',
                'price' => 1999,
                'old_price' => 2999,
                'discount' => 33,
                'rating' => 4.8,
                'reviews' => 74,
                'image' => 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Blue', 'Red'],
                'color_codes' => ['#1B4F72', '#78281F'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-MAX-006',
                'material' => 'Fine Micro-Pleated Chiffon',
                'fit' => 'High Neck Trapeze Gown',
                'care' => 'Specialist Dry Clean Only',
                'description' => 'Accordion pleats flow from a polished high neck collar into an ethereal, featherweight silhouette.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 31,
                'name' => 'Block Printed Festive Cotton Flare Maxi',
                'category' => 'Maxi',
                'subcategory' => 'Floral Maxi',
                'price' => 1349,
                'old_price' => 2099,
                'discount' => 36,
                'rating' => 4.5,
                'reviews' => 103,
                'image' => 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['Green', 'Yellow'],
                'color_codes' => ['#1E8449', '#F39C12'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-MAX-007',
                'material' => 'Pure Mulmul Cotton',
                'fit' => 'Empire Fit with Flare',
                'care' => 'Machine Wash Cold',
                'description' => 'Traditional block motifs rendered in a contemporary maxi dress silhouette. Lightweight, breathable, and deeply comforting.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 32,
                'name' => 'Smocked Bustier Slit Beach Maxi Dress',
                'category' => 'Maxi',
                'subcategory' => 'Casual Maxi',
                'price' => 1099,
                'old_price' => 1699,
                'discount' => 35,
                'rating' => 4.5,
                'reviews' => 88,
                'image' => 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Pink', 'White'],
                'color_codes' => ['#FADBD8', '#FFFFFF'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-MAX-008',
                'material' => 'Soft Spun Rayon',
                'fit' => 'Smocked Elastic Bodice',
                'care' => 'Machine Wash Cold',
                'description' => 'Features an ultra-flexible smocked upper body that fits comfortably across all body types, finished with a subtle side leg slit.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],

            // NIGHTWEAR (33-40)
            [
                'id' => 33,
                'name' => 'Notch Collar Cotton Button-Down Night Suit',
                'category' => 'Nightwear',
                'subcategory' => 'Night Suits',
                'price' => 1099,
                'old_price' => 1699,
                'discount' => 35,
                'rating' => 4.8,
                'reviews' => 260,
                'image' => 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['Pink', 'Blue', 'White'],
                'color_codes' => ['#FADBD8', '#AED6F1', '#FFFFFF'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-NGH-001',
                'material' => '100% Breathable Modal Cotton',
                'fit' => 'Relaxed Lounge Cut with Elastic Pyjamas',
                'care' => 'Machine Wash Cold',
                'description' => 'Classic piped notch lapel shirt paired with comfort-fit pyjamas featuring deep functional side pockets.',
                'featured' => true,
                'best_seller' => true,
                'trending' => true,
            ],
            [
                'id' => 34,
                'name' => 'Floral Botanical Kaftan Night Dress',
                'category' => 'Nightwear',
                'subcategory' => 'Night Dresses',
                'price' => 799,
                'old_price' => 1299,
                'discount' => 38,
                'rating' => 4.7,
                'reviews' => 195,
                'image' => 'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Green', 'Pink'],
                'color_codes' => ['#A9DFBF', '#FADBD8'],
                'badge' => 'Trending',
                'stock' => true,
                'sku' => 'ZYR-NGH-002',
                'material' => 'Super Soft Washed Rayon',
                'fit' => 'One Size Relaxed Flow with Drawstring',
                'care' => 'Machine Wash Warm',
                'description' => 'Airy kimono sleeves with an adjustable internal waist tie drawstring for cozy evenings and lazy Sunday mornings.',
                'featured' => true,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 35,
                'name' => 'Silky Satin Cami & Shorts Loungewear Set',
                'category' => 'Nightwear',
                'subcategory' => 'Lounge Wear',
                'price' => 899,
                'old_price' => 1399,
                'discount' => 36,
                'rating' => 4.6,
                'reviews' => 150,
                'image' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Pink', 'Black', 'Blue'],
                'color_codes' => ['#F1948A', '#1A1A1A', '#2E4053'],
                'badge' => 'New',
                'stock' => true,
                'sku' => 'ZYR-NGH-003',
                'material' => 'Glossy Ultra-Smooth Satin',
                'fit' => 'Gentle Camisole & Ruffled Hem Shorts',
                'care' => 'Hand Wash Cold',
                'description' => 'Featherweight satin that glides over the skin with delicate scalloped lace trims and adjustable shoulder straps.',
                'featured' => false,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 36,
                'name' => 'Printed Pure Cotton Sleepwear Maxi Nighty',
                'category' => 'Nightwear',
                'subcategory' => 'Cotton Nightwear',
                'price' => 649,
                'old_price' => 999,
                'discount' => 35,
                'rating' => 4.5,
                'reviews' => 310,
                'image' => 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'colors' => ['Blue', 'Pink', 'Yellow'],
                'color_codes' => ['#AED6F1', '#FADBD8', '#FCF3CF'],
                'badge' => 'Best Seller',
                'stock' => true,
                'sku' => 'ZYR-NGH-004',
                'material' => '100% Pure Combed Cotton',
                'fit' => 'Ankle Length Roomy Fit',
                'care' => 'Machine Wash Normal',
                'description' => 'Everyday staple night dress with front button placket, short sleeves, and soothing Indian block prints.',
                'featured' => false,
                'best_seller' => true,
                'trending' => false,
            ],
            [
                'id' => 37,
                'name' => 'Tie-Dye Oversized Sleep Tee & Jogger Set',
                'category' => 'Nightwear',
                'subcategory' => 'Lounge Wear',
                'price' => 1149,
                'old_price' => 1799,
                'discount' => 36,
                'rating' => 4.6,
                'reviews' => 84,
                'image' => 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Pink', 'Blue'],
                'color_codes' => ['#F5CBA7', '#D4E6F1'],
                'badge' => 'Trending',
                'stock' => true,
                'sku' => 'ZYR-NGH-005',
                'material' => '100% French Terry Cotton',
                'fit' => 'Oversized Slouchy Fit',
                'care' => 'Machine Wash Cold',
                'description' => 'Trendy pastel tie-dye drops with an oversized boxy crew neck tee and matching cuffed ankle joggers.',
                'featured' => true,
                'best_seller' => false,
                'trending' => true,
            ],
            [
                'id' => 38,
                'name' => 'Polka Dot Buttoned Cotton Pyjama Suit',
                'category' => 'Nightwear',
                'subcategory' => 'Night Suits',
                'price' => 999,
                'old_price' => 1499,
                'discount' => 33,
                'rating' => 4.4,
                'reviews' => 120,
                'image' => 'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Black', 'White', 'Pink'],
                'color_codes' => ['#1A1A1A', '#FFFFFF', '#FADBD8'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-NGH-006',
                'material' => 'Soft Bio-Washed Cotton',
                'fit' => 'Comfortable Straight Cut',
                'care' => 'Machine Wash Cold',
                'description' => 'Playful polka dot print with contrasting white piped edges and an elastic waistband pyjama.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 39,
                'name' => 'Elegance Full Length Satin Robe & Slip Gown',
                'category' => 'Nightwear',
                'subcategory' => 'Night Dresses',
                'price' => 1599,
                'old_price' => 2499,
                'discount' => 36,
                'rating' => 4.8,
                'reviews' => 110,
                'image' => 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Pink', 'Black', 'Red'],
                'color_codes' => ['#E8B4B8', '#1A1A1A', '#78281F'],
                'badge' => 'Sale',
                'stock' => true,
                'sku' => 'ZYR-NGH-007',
                'material' => 'Glossy Butter Satin',
                'fit' => '2-Piece Robe & Slip Gown',
                'care' => 'Dry Clean or Gentle Cold Hand Wash',
                'description' => 'Two-piece bedroom luxury set featuring a floor-grazing kimono wrap robe and an adjustable camisole slip gown.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ],
            [
                'id' => 40,
                'name' => 'Striped Woven Cotton Lounge Pyjamas',
                'category' => 'Nightwear',
                'subcategory' => 'Cotton Nightwear',
                'price' => 599,
                'old_price' => 899,
                'discount' => 33,
                'rating' => 4.3,
                'reviews' => 95,
                'image' => 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
                'images' => [
                    'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80'
                ],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'colors' => ['Blue', 'White'],
                'color_codes' => ['#5DADE2', '#FFFFFF'],
                'badge' => '',
                'stock' => true,
                'sku' => 'ZYR-NGH-008',
                'material' => 'Yarn-Dyed 100% Breathable Cotton',
                'fit' => 'Relaxed Pyjama Bottoms',
                'care' => 'Machine Wash Warm',
                'description' => 'Classic vertical stripes with an elastic waistband, cotton twill drawstring, and deep dual pockets.',
                'featured' => false,
                'best_seller' => false,
                'trending' => false,
            ]
        ];
    }

    public static function find(int $id): ?array
    {
        $products = self::getProducts();
        foreach ($products as $product) {
            if ($product['id'] === $id) {
                return $product;
            }
        }
        return null;
    }

    public static function getByCategory(string $categorySlug): array
    {
        $categoryMap = [
            'tops' => 'Tops',
            'leggings' => 'Leggings',
            'kurtis' => 'Kurtis',
            'maxi' => 'Maxi',
            'nightwear' => 'Nightwear'
        ];

        $targetCategory = $categoryMap[strtolower($categorySlug)] ?? ucfirst($categorySlug);

        return array_values(array_filter(self::getProducts(), function ($product) use ($targetCategory) {
            return strcasecmp($product['category'], $targetCategory) === 0;
        }));
    }

    public static function getFeatured(): array
    {
        return array_values(array_filter(self::getProducts(), function ($product) {
            return !empty($product['featured']);
        }));
    }

    public static function getBestSellers(): array
    {
        return array_values(array_filter(self::getProducts(), function ($product) {
            return !empty($product['best_seller']);
        }));
    }

    public static function getNewArrivals(int $limit = 8): array
    {
        $products = self::getProducts();
        $newArrivals = array_values(array_filter($products, function ($product) {
            return ($product['badge'] ?? '') === 'New' || !empty($product['trending']);
        }));
        return array_slice($newArrivals, 0, $limit);
    }

    public static function getCoupons(): array
    {
        return [
            'WELCOME10' => ['discount' => 10, 'type' => 'percentage', 'description' => '10% off for new shoppers'],
            'SAVE20'    => ['discount' => 20, 'type' => 'percentage', 'description' => 'Flat 20% off on all orders'],
            'FASHION15' => ['discount' => 15, 'type' => 'percentage', 'description' => '15% off season discount'],
        ];
    }
}
